site:
  name:             Dinin
title_site:       Modele de projet pour Dev-Crea
describ_site:     >
  Application faisant office d'exemple pour la cr√©ation de projet Dev-Crea.

host:           <%= ENV['HOST']%>
port:           <%= ENV['PORT']%>
protocol:       <%= ENV['PROTOCOL']%>

mailer:
  user:         <%= ENV['MAILER_USER'] %>
  password:     <%= ENV['MAILER_PASSWORD'] %>
  domain:       <%= ENV['HOST'] %>
  address:      <%= ENV['MAILER_ADDRESS'] %>
